// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_item_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderItemModel _$OrderItemModelFromJson(Map<String, dynamic> json) =>
    OrderItemModel(
      POSID: json['POSID'] as String?,
      OperatorNo: json['OperatorNo'] as int?,
      Covers: json['Covers'] as int?,
      TableNo: json['TableNo'] as String?,
      SalesNo: json['SalesNo'] as int?,
      SplitNo: json['SplitNo'] as int?,
      SalesRef: json['SalesRef'] as int?,
      PLUSalesRef: json['PLUSalesRef'] as int?,
      ItemSeqNo: json['ItemSeqNo'] as int?,
      PLUNo: json['PLUNo'] as String?,
      Department: json['Department'] as int?,
      SDate: json['SDate'] as String?,
      STime: json['STime'] as String?,
      Quantity: json['Quantity'] as int?,
      ItemName: json['ItemName'] as String?,
      ItemName_Chinese: json['ItemName_Chinese'] as String?,
      ItemAmount: json['ItemAmount'] as int?,
      PaidAmount: json['PaidAmount'] as int?,
      ChangeAmount: json['ChangeAmount'] as int?,
      Gratuity: json['Gratuity'] as int?,
      Tax0: json['Tax0'] as int?,
      Tax1: json['Tax1'] as int?,
      Tax2: json['Tax2'] as int?,
      Tax3: json['Tax3'] as int?,
      Tax4: json['Tax4'] as int?,
      Tax5: json['Tax5'] as int?,
      Tax6: json['Tax6'] as int?,
      Tax7: json['Tax7'] as int?,
      Tax8: json['Tax8'] as int?,
      Tax9: json['Tax9'] as int?,
      Adjustment: json['Adjustment'] as int?,
      DiscountType: json['DiscountType'] as String?,
      DiscountPercent: json['DiscountPercent'] as String?,
      Discount: json['Discount'] as int?,
      PromotionId: json['PromotionId'] as int?,
      PromotionType: json['PromotionType'] as String?,
      PromotionSaving: json['PromotionSaving'] as int?,
      TransMode: json['TransMode'] as String?,
      RefundID: json['RefundID'] as int?,
      TransStatus: json['TransStatus'] as String?,
      FunctionID: json['FunctionID'] as int?,
      SubFunctionID: json['SubFunctionID'] as int?,
      MembershipID: json['MembershipID'] as int?,
      LoyaltyCardNo: json['LoyaltyCardNo'] as String?,
      CustomerID: json['CustomerID'] as String?,
      CardScheme: json['CardScheme'] as String?,
      CreditCardNo: json['CreditCardNo'] as String?,
      AvgCost: (json['AvgCost'] as num?)?.toDouble(),
      RecipeId: json['RecipeId'] as int?,
      PriceShift: json['PriceShift'] as int?,
      CategoryId: json['CategoryId'] as int?,
      TransferredTable: json['TransferredTable'] as String?,
      TransferredOp: json['TransferredOp'] as int?,
      KitchenPrint1: json['KitchenPrint1'] as int?,
      KitchenPrint2: json['KitchenPrint2'] as int?,
      KitchenPrint3: json['KitchenPrint3'] as int?,
      RedemptionItem: json['RedemptionItem'] as int?,
      PointsRedeemed: json['PointsRedeemed'] as int?,
      ShiftID: json['ShiftID'] as int?,
      PrintFreePrep: json['PrintFreePrep'] as int?,
      PrintPrepWithPrice: json['PrintPrepWithPrice'] as int?,
      Preparation: json['Preparation'] as int?,
      FOCItem: json['FOCItem'] as int?,
      FOCType: json['FOCType'] as String?,
      ApplyTax0: json['ApplyTax0'] as int?,
      ApplyTax1: json['ApplyTax1'] as int?,
      ApplyTax2: json['ApplyTax2'] as int?,
      ApplyTax3: json['ApplyTax3'] as int?,
      ApplyTax4: json['ApplyTax4'] as int?,
      ApplyTax5: json['ApplyTax5'] as int?,
      ApplyTax6: json['ApplyTax6'] as int?,
      ApplyTax7: json['ApplyTax7'] as int?,
      ApplyTax8: json['ApplyTax8'] as int?,
      ApplyTax9: json['ApplyTax9'] as int?,
      LnkTo: json['LnkTo'] as String?,
      BuyXfreeYapplied: json['BuyXfreeYapplied'] as int?,
      RndingAdjustments: json['RndingAdjustments'] as int?,
      Setmenu: json['Setmenu'] as int?,
      SetMenuRef: json['SetMenuRef'] as int?,
      Instruction: json['Instruction'] as String?,
      PostSendVoid: json['PostSendVoid'] as int?,
      TblHold: json['TblHold'] as int?,
      DepositID: json['DepositID'] as int?,
      TSalesRef: json['TSalesRef'] as int?,
      TSalesNo: json['TSalesNo'] as int?,
      TSplitNo: json['TSplitNo'] as int?,
      RentalItem: json['RentalItem'] as int?,
      RentToDate: json['RentToDate'] as String?,
      RentToTime: json['RentToTime'] as String?,
      MinsRented: json['MinsRented'] as int?,
      SeatNo: json['SeatNo'] as int?,
      SalesAreaID: json['SalesAreaID'] as String?,
      BusinessDate: json['BusinessDate'] as String?,
      ServerNo: json['ServerNo'] as int?,
      OperatorFOC: json['OperatorFOC'] as int?,
      OperatornoFirst: json['OperatornoFirst'] as int?,
      cc_promo1: json['cc_promo1'] as String?,
      cc_promo2: json['cc_promo2'] as String?,
      Voucherseqno: json['Voucherseqno'] as int?,
      tbl_servedtime: json['tbl_servedtime'] as String?,
      ServedStatus: json['ServedStatus'] as int?,
      comments: json['comments'] as int?,
      Switchid: json['Switchid'] as int?,
      OperatorPromo: json['OperatorPromo'] as int?,
      Trackprep: json['Trackprep'] as int?,
      RentFromTime: json['RentFromTime'] as String?,
      promptRentalWarning: json['promptRentalWarning'] as int?,
      CPRVoucherNo: json['CPRVoucherNo'] as String?,
      ForeignPaidAmnt: json['ForeignPaidAmnt'] as int?,
      TaxTag: json['TaxTag'] as String?,
      CaptainOrderNo: json['CaptainOrderNo'] as String?,
      KDSPrint: json['KDSPrint'] as int?,
    );

Map<String, dynamic> _$OrderItemModelToJson(OrderItemModel instance) =>
    <String, dynamic>{
      'POSID': instance.POSID,
      'OperatorNo': instance.OperatorNo,
      'Covers': instance.Covers,
      'TableNo': instance.TableNo,
      'SalesNo': instance.SalesNo,
      'SplitNo': instance.SplitNo,
      'SalesRef': instance.SalesRef,
      'PLUSalesRef': instance.PLUSalesRef,
      'ItemSeqNo': instance.ItemSeqNo,
      'PLUNo': instance.PLUNo,
      'Department': instance.Department,
      'SDate': instance.SDate,
      'STime': instance.STime,
      'Quantity': instance.Quantity,
      'ItemName': instance.ItemName,
      'ItemName_Chinese': instance.ItemName_Chinese,
      'ItemAmount': instance.ItemAmount,
      'PaidAmount': instance.PaidAmount,
      'ChangeAmount': instance.ChangeAmount,
      'Gratuity': instance.Gratuity,
      'Tax0': instance.Tax0,
      'Tax1': instance.Tax1,
      'Tax2': instance.Tax2,
      'Tax3': instance.Tax3,
      'Tax4': instance.Tax4,
      'Tax5': instance.Tax5,
      'Tax6': instance.Tax6,
      'Tax7': instance.Tax7,
      'Tax8': instance.Tax8,
      'Tax9': instance.Tax9,
      'Adjustment': instance.Adjustment,
      'DiscountType': instance.DiscountType,
      'DiscountPercent': instance.DiscountPercent,
      'Discount': instance.Discount,
      'PromotionId': instance.PromotionId,
      'PromotionType': instance.PromotionType,
      'PromotionSaving': instance.PromotionSaving,
      'TransMode': instance.TransMode,
      'RefundID': instance.RefundID,
      'TransStatus': instance.TransStatus,
      'FunctionID': instance.FunctionID,
      'SubFunctionID': instance.SubFunctionID,
      'MembershipID': instance.MembershipID,
      'LoyaltyCardNo': instance.LoyaltyCardNo,
      'CustomerID': instance.CustomerID,
      'CardScheme': instance.CardScheme,
      'CreditCardNo': instance.CreditCardNo,
      'AvgCost': instance.AvgCost,
      'RecipeId': instance.RecipeId,
      'PriceShift': instance.PriceShift,
      'CategoryId': instance.CategoryId,
      'TransferredTable': instance.TransferredTable,
      'TransferredOp': instance.TransferredOp,
      'KitchenPrint1': instance.KitchenPrint1,
      'KitchenPrint2': instance.KitchenPrint2,
      'KitchenPrint3': instance.KitchenPrint3,
      'RedemptionItem': instance.RedemptionItem,
      'PointsRedeemed': instance.PointsRedeemed,
      'ShiftID': instance.ShiftID,
      'PrintFreePrep': instance.PrintFreePrep,
      'PrintPrepWithPrice': instance.PrintPrepWithPrice,
      'Preparation': instance.Preparation,
      'FOCItem': instance.FOCItem,
      'FOCType': instance.FOCType,
      'ApplyTax0': instance.ApplyTax0,
      'ApplyTax1': instance.ApplyTax1,
      'ApplyTax2': instance.ApplyTax2,
      'ApplyTax3': instance.ApplyTax3,
      'ApplyTax4': instance.ApplyTax4,
      'ApplyTax5': instance.ApplyTax5,
      'ApplyTax6': instance.ApplyTax6,
      'ApplyTax7': instance.ApplyTax7,
      'ApplyTax8': instance.ApplyTax8,
      'ApplyTax9': instance.ApplyTax9,
      'LnkTo': instance.LnkTo,
      'BuyXfreeYapplied': instance.BuyXfreeYapplied,
      'RndingAdjustments': instance.RndingAdjustments,
      'Setmenu': instance.Setmenu,
      'SetMenuRef': instance.SetMenuRef,
      'Instruction': instance.Instruction,
      'PostSendVoid': instance.PostSendVoid,
      'TblHold': instance.TblHold,
      'DepositID': instance.DepositID,
      'TSalesRef': instance.TSalesRef,
      'TSalesNo': instance.TSalesNo,
      'TSplitNo': instance.TSplitNo,
      'RentalItem': instance.RentalItem,
      'RentToDate': instance.RentToDate,
      'RentToTime': instance.RentToTime,
      'MinsRented': instance.MinsRented,
      'SeatNo': instance.SeatNo,
      'SalesAreaID': instance.SalesAreaID,
      'BusinessDate': instance.BusinessDate,
      'ServerNo': instance.ServerNo,
      'OperatorFOC': instance.OperatorFOC,
      'OperatornoFirst': instance.OperatornoFirst,
      'cc_promo1': instance.cc_promo1,
      'cc_promo2': instance.cc_promo2,
      'Voucherseqno': instance.Voucherseqno,
      'tbl_servedtime': instance.tbl_servedtime,
      'ServedStatus': instance.ServedStatus,
      'comments': instance.comments,
      'Switchid': instance.Switchid,
      'OperatorPromo': instance.OperatorPromo,
      'Trackprep': instance.Trackprep,
      'RentFromTime': instance.RentFromTime,
      'promptRentalWarning': instance.promptRentalWarning,
      'CPRVoucherNo': instance.CPRVoucherNo,
      'ForeignPaidAmnt': instance.ForeignPaidAmnt,
      'TaxTag': instance.TaxTag,
      'CaptainOrderNo': instance.CaptainOrderNo,
      'KDSPrint': instance.KDSPrint,
    };
