import 'dart:core';

class GlobalConfig {
  static String token = "";
  static String username = "";

  static String PLUNumber = '';
  static String PLUName = '';

  static int salesNo = 1;
  static int splitNo = 1;
  static int cover = 0;
  static String tableNo = "3";
  static String rcptNo = "A2200000014";
  //static bool ShowFunc = false;
  //static bool ShowPromo = false;
  //static bool ShowBillFOC = false;
  //static bool ShowDisc = false;

  static String TransMode = "REG";

  static int operatorNo = 1;
  static String operatorName = "Admin";
  static int MaxVoids = 9999;
  static int MaxVoidsPerSale = 9999;
  static bool AllVoid = true;
  static bool BillFOC = true;
  static bool VoidPromotion = true;
  static bool opPromotion = true;
  static bool Manager = true;
  static bool XReport = true;
  static bool ZReport = true;
  static bool VoidPayments = true;
  static bool LogoutAfterSales = true;
  static bool ItemFOC = true;
  static bool OpPrinterSetting = true;

  static int TableNoInt = 0;
  static String ErrMsg = "";
  static String ErrMsg2 = "";

  static String CategoryName = "";
  static int checkTableOpen = 0;
  static int checkItemOrder = 0;
  static int PrinterLength = 0;

  static int CustomKeyboard =
      0; //1:All Void, 2:Item Void, 3:CustomerID, 33:CustomerIDFOCBill, 4:Remarks, 5:Comments FOC
  static int PinAuth =
      0; //1:FOC Bill, 2:FOC Item, 3:Customer Display, 4:Kitchen Display, 5:All Void, 6:Void Promotion
  static int SplitQuantity = 0; //1:Split Quantity, 2:Split Void Quantity
  static bool ClickMenu =
      true; //true: menu enabled click, false: menu disabled click
  static bool ButtonClick = true;
  static int ChangeLayout = 1; //1:Pay Layout, 2:FOC Bill Layout
  static int CoverView = 0; //1:Table Management, 2:Quick Service
  static bool IsPrintInit = false;
}

class POSDefault {
  static late bool taxInclusive = true;
  static bool blnSplitQuantity = false;
  static bool blnSplitKPStatus = false;

  static String ExecFilePath = '';
  static bool FiPo = false;
  static double FiPoAmount = 0;
  static bool ForceZDay = false;
  static bool ForceZShift = false;
  static bool enableStock = false;
  static bool blnGraphicsButton = false;
  static bool RndingAdjUp = false;
  static bool RndingAdjDown = false;
  static bool PresettleRound = false;
  static bool blnRentalCalculation = false;
  static bool blnPrintBottleRcpt = false;
  static int tblCleaningTime = 0;
  static bool blnIntrounding = false;
  static double Denumeration = 0;
  static bool TrackFoodServed = false;
  static double MaxOrderAmount = 0;
  static double MaxOrderQty = 0;
  static bool TaxInclusive = false;
  static bool PLUNumbersOnly = false;
  static String temp_BusinessEndTime = '';
  static String temp_businessStartTime = '';
  static bool blnTableManagement = false;
  static bool Cpr = false;
  static bool LiberteCPR = false;
  static bool printlogo = false;
  static bool blnPostVoidReason = false;
  static bool blnEnableThumper = false;
  static String FingerprintLogo = '';
  static bool enablePGP = false;
  static bool blnEncryptdbPath = false;
  static String SectorLogonPwd = '';
  static bool EnableMemOffline = false;
  static bool blnReciptConsolidate = false;
  static bool blnRoundAllMedia = false;
  static bool prmnPOS = false;
  static String mycurrency = '';
  static bool printKPWhenHoldTable = false;
  static int minFPScore = 0;
  static double depositvalue = 0;
  static bool blnPrintKPRfnd = false;
  static String opXPALogin = '';
  static bool blnKDS = false;
  static double CP_UTF8 = 0;
  static int viewTransOrderBy = 0;
  static bool LoginConfirmation = false;
  static double ezBalanceDebitInterval = 0;
  static double EzSettlementInterval = 0;
  static bool blnForceZdayDaily = false;
  static bool blnSplitPrepItemQty = false;
  static bool blnPrinterRedirect = false;
  static bool blnAttndByShift = false;
  static bool blnUnBlockFOCBillValidation = false;
  static bool blnNTUCIfMemberPromo = false;
  static String strNTUCFirstLine = '';
  static String strNTUCSecondLine = '';
  static bool blnPartialRcptConsolidate = false;
  static bool blnSetmenuIndividual = false;
  static bool blnShutdown = false;
  static bool blnMinimizeWin = false;
  static bool PhilippineTax = false;
  static double TScreenRefreshTime = 0;
  static double IntScroll = 0;
  static bool RfndPrompt4RcptNo = false;
  static bool blnPrintUnluckyVoucher = false;
  static bool blnPrintBarcode = false;
  static bool BlnLastVoid = false;
  static bool GenerateReceiptNoEnd = false;
  static bool blnLockCashlessState = false;
  static bool PrintKPWhenVoid = false;
  static bool BlockPLUSoldOut = false;
  static bool ForcePLUCoverQty = false;
  static int MaxNarrative = 0;
  static bool g_blnEnableAevitas = false;
  static String g_strFolderAevitas = '';
  static int g_intFormatAevitas = 0;
  static bool g_blnOrderItemCashlessCheck = false;
  static bool OffMemTrans = false;
  static String StrBusinessDate = '';
  static bool PLUImageDB = false;
}

class POSDtls {
  static late int categoryID = 1;
  static late String deviceNo = "1";
  static late String posType;
  static late String strSalesAreaID = "LOUN";
  static late String selTermDSN;
  static late String srvrDSN;
  static late String printRcpt;
  static late String hpyHr1;
  static late String hpyHr2;
  static late String hpyHr3;
  static late String hpyStart1;
  static late String hpyEnd1;
  static late String hpyStart2;
  static late String hpyEnd2;
  static late String hpyStart3;
  static late String hpyEnd3;
  static late int defCtgryID;
  static late int ctgryID;
  static late int mnuLvl;
  static late String tblNameType;
  static late int firstTable;
  static late int lastTable;
  static late bool tblAutoOnly;
  static late bool forceTable;
  static late bool blnForceCovertracking;
  static late bool xzSms;
  static late String zxSmsDevice;
  static late String dialInprovider;
  static late String providerProtocol;
  static late String providerPassword;
  static late bool FingerPrint;
  static late bool sdkPOS;
  static late bool PrintRental;
  static late bool PrintVoidRemarksKP;
  static late bool PluNoItem;
  static late bool FingerPrintMem;
  static late bool FingerPrintOP;
  static late bool ForceServerNo;
  static late bool blnForceSalesCategory;
  static late bool DualFnPrinter;
  static late bool EnableSysSetUp;
  static late bool PrintVoids;
  static late bool PrintFreeItems;
  static late bool PrintUnitPrice;
  static late bool PrintGroupsubtotal;
  static late bool PrintSalesCategory;
  static late bool PrintDeptSubTotal;
  static late bool PrintSalesCtgSubTotal;
  static late bool PrintGroup;
  static late bool PrintDepartment;
  static late bool KPPrintGroup;
  static late bool KPPrintDepartment;
  static late bool KPOrderRemarks;
  static late bool PrintRounding;
  static late bool PrintTax;
  static late bool PrintTotalTax;
  static late String TotalTaxTitle;
  static late bool EnBell;
  static late String BColor;
  static late String FColor;
  static late bool PrintPrmnDtls;
  static late bool PrintPrmnSummary;
  static late bool PrintFreePrep;
  static late bool PrintFreePLU;
  static late bool PrintPrepWithPrice;
  static late bool PrintTimeAttend;
  static late int AutoTblStart;
  static late int AutoTblEnd;
  static late bool Kitchen;
  static late bool ApplyPrmn;
  static late int DefPShift = 1;
  static late String PShift = "1";
  static late bool CustDisplay;
  static late String CustDisp1;
  static late String CustDisp2;
  static late int CustDispPort;
  static late bool DispScroll;
  static late int ClosedBillCnt;
  static late int ReprintBillCnt;
  static late int PreprintBillCnt;
  static late int AllVoidBillCnt;
  static late int XreportCnt;
  static late int ZreportCnt;
  static late bool OrderStation;
  static late bool PLU_BillDiscount;
  static late bool XZALLPOS;
  static late bool xzGroup;
  static late bool xzHistory;
  static late bool xzOperator;
  static late bool xzPluFoc;
  static late bool xzRemarks;
  static late bool blnWeighingScale;
  static late int intWeighingPort;
  static late int intWeighScaleType;
  static late int WeighScaleDec;
  static late int WeighScaleDecimal;
  static late bool blnPrintLstOpName;
  static late bool printFirstservername;
  static late bool blnNetsScan;
  static late int intNetsPort;
  static late int intCreditCardPort;
  static late int intCreditCardTimeOut;
  static late String strPOSButtonColor;
  static late bool blnTblMangTime;
  static late String strTransTblKpID;
  static late bool blnTransTbl_AllPrinter;
  static late bool printrcptno;
  static late bool PrintRcptTime;
  static late bool PrintTableNo;
  static late bool blnKPPrintConsolidate;
  static late bool blnKPPrintIndividual;
  static late bool blnKPPrintMaster;
  static late bool blnKPPrintTransferTable;
  static late bool blnKPPrintStickerRcpt;
  static late bool blnKPPrintID = true;
  static late bool blnKPMasterPrintID;
  static late bool blnKPPrintPrepQty;
  static late bool blnKPPrintCover;
  static late bool blnKPPrintPLUNo;
  static late bool blnKPPrintPrice;
  static late bool blnKPPrintPriceTotal;
  static late bool blnKPPrintSideway;
  static late bool blnKPPrintBarcode;
  static late bool blnKPPrintAutoSplitQty;
  static late bool blnKPPartialConsolidate = true;
  static late bool blnKPPrintBigTableNo;
  static late bool blnKPPrintRefundItem;
  static late bool blnKPPrintCounter;
  static late bool blnPrint;
  static late bool PrintTblRemarks;
  static late bool MasterKPPrintTblRemarks;
  static late bool blnMultiDrawer;
  static late String DrawerName;
  static late bool blnDumpDrawer;
  static late String DrawerPort;
  static late int DrawerValue;
  static late bool viewDot;
  static late String stritemlistBColor;
  static late String strItemListFColor;
  static late int intItemListFontSize;
  static late bool blnItemListBold;
  static late String strNumpadBColor;
  static late int intNumpadFontSize;
  static late bool blnNumpadBold;
  static late bool BlnCreditCard_Scan;
  static late bool blnpoolportno;
  static late int intPoolPortNo;
  static late int intlanguage;
  static late int intlanguageop;
  static late bool ForceFiPo;
  static late int intItemRight;
  static late int intItemBottom;
  static late int intMenuRight;
  static late int intMenuBottom;
  static late bool DispWelcomeOnly;
  static late bool StartWithOpenTbls;
  static late bool TBLManagement;
  static late int NumKpBHdrLines;
  static late bool LineBetKPHdr;
  static late bool LineBetKPItems;
  static late bool LineBetKPMsgHdr;
  static late bool LineBetKPMessage;
  static late bool ForceSeatNo;
  static late String SignInName;
  static late bool blnSecondScreen;
  static late bool blnViewOrderGrid;
  static late String GridHcolor;
  static late String GridOcolor;
  static late String GridEcolor;
  static late String GridFcolor;
  static late String GridMColor;
  static late String GridPcolor;
  static late String GridCColor;
  static late String GridFocColor;
  static late String GridDcolor;
  static late String SecondBcolor;
  static late String SecondFcolor;
  static late String firstPic;
  static late String SecondPic;
  static late String CompanyPic;
  static late String TablePic;
  static late String ScreenHeader1;
  static late String ScreenHeader2;
  static late String ScreenHeader3;
  static late bool blnSmartCard;
  static late int SmartcardPort;
  static late bool blnAutoReceivedPOS;
  static late String strAutoReceivedPOS;
  static late bool SmartCardMem;
  static late bool SmartCardOP;
  static late bool blnSmartCardTopUp;
  static late int cntVisitWarning;
  static late bool blnTicketTag;
  static late bool blnPrintTotalQty;
  static late bool printBalancePoints;
  static late bool blnXPA;
  static late bool blnForceSalesCategorySellband;
  static late int RentalWarning;
  static late bool printZeroPrice;
  static late bool blnEzlink;
  static late int EzlinkPort;
  static late bool blnViewTableNo;
  static late int PoolTableLoc;
  static late String strMinTimeForZDay;
  static late bool blnMinTimeOverMidNight;
  static late bool blnDisplayMemberFav;
  static late bool blnDisplayMemberPurchase;
  static late bool blnBixolonCustDisp;
  static late bool blnViewRePrintAll;
  static late bool blnPrinXZRemarks;
  static late bool blnPrintVAT;
  static late bool blnPrintCaptainOrder;
  static late String strScroll;
  static late bool printOfficial;
  static late bool XZprintCollected;
  static late String LabelTable = '';
  static late bool UpdateRsvn;
  static late bool BlnAutoPromotion;
  static late bool BlnFreeItems;
  static late bool PrintZeroSales;
  static late bool EnableCombo;
  static late String BarcodeWeight;
  static late String BarcodePrice;
  static late int BarcodeWeightDec;
  static late int BarcodeWeightDecimal;
  static late bool blnNewTablePopUp;
  static late String strPopUpMsg;
  static late bool blnFPOD;
  static late bool SDK2POS;
  static late int SecondScreenFontsize;
  static late bool RcptManualPrinterId;
  static late bool g_blnPreRcptDblSize;
  static late String g_strPreRcptComment;
  static late bool blnPrintLstServerName;
  static late bool ConsolidateMedia;
  static late int OMRPort;
  static late bool g_blnForceCloseDrawer;
  static late bool ZipCodeTableNo;
  static late bool PrintRcptTitle;
  static late bool AskNarrative;
  static late double AskNarrativeAmount;
  static late bool SendBillToEmail;
  static late bool PrintTaxTitle;
  static late bool g_blnTabletScreen;

  static late String refDtName;
  static late String refTimeName;
  static late bool AlertPrevDayPendTbls;
  static late int SecID;
  static late bool blnKPPrintStickerCheck;
}

class InitSalesVar {
  static late int NCover = 0;
  static late String TransMode = "REG";
  static late String LoyaltyCardNo = "";
  static late int SeatNo = 0;
  static late int RefundID = 0;
  static late String strTableName = "";

  //Tax
  static late bool ApplyTax0 = false;
  static late bool ApplyTax1 = false;
  static late bool ApplyTax2 = false;
  static late bool ApplyTax3 = false;
  static late bool ApplyTax4 = false;
  static late bool ApplyTax5 = false;
  static late bool ApplyTax6 = false;
  static late bool ApplyTax7 = false;
  static late bool ApplyTax8 = false;
  static late bool ApplyTax9 = false;
  static late double TTax0 = 0.0;
  static late double TTax1 = 0.0;
  static late double TTax2 = 0.0;
  static late double TTax3 = 0.0;
  static late double TTax4 = 0.0;
  static late double TTax5 = 0.0;
  static late double TTax6 = 0.0;
  static late double TTax7 = 0.0;
  static late double TTax8 = 0.0;
  static late double TTax9 = 0.0;

  //Member
  static late int memId = 0;
}
