// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'operator_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OperatorModel _$OperatorModelFromJson(Map<String, dynamic> json) =>
    OperatorModel(
      json['OperatorNo'] as int,
      json['OperatorName'] as String,
      json['PIN'] as String,
      json['MultiOp'] as int,
      json['MaxVoids'] as int,
      json['MaxVoidsPerSale'] as int,
      json['SelectableVoids'] as int,
      json['VoidLastItem'] as int,
      json['AllVoid'] as int,
      json['VoidPayments'] as int,
      json['DiscItemPer'] as int,
      json['DiscItemAmt'] as int,
      json['RepeatBillDisc'] as int,
      json['FreeOfCharge'] as int,
      json['SuspendBill'] as int,
      json['ExemptTax'] as int,
      json['StayTaxEmptOn'] as int,
      json['RecallBill'] as int,
      json['AdjustBill'] as int,
      json['ReprintReceipt'] as int,
      json['PriceShift'] as int,
      json['OpenPriceShift'] as int,
      json['XReport'] as int,
      json['ZReport'] as int,
      json['TransferSale'] as int,
      json['TransferTable'] as int,
      json['Refunds'] as int,
      json['RedeemPoints'] as int,
      json['ZeroSales'] as int,
      json['CardNo'] as String,
      json['Manager'] as int,
      json['ForceCashDeclare'] as int,
      json['OpenAnyTable'] as int,
      json['TBLReservation'] as int,
      json['MembershipNum'] as int,
      json['ActivePromotion'] as int,
      json['PromotionEnds'] as String,
      json['ClearAndStore'] as int,
      json['EditSysSetup'] as int,
      json['PreSettlementRcpt'] as int,
      json['LogoutAfterSale'] as int,
      json['LogoutOnTableHold'] as int,
      json['EditKitchenMessage'] as int,
      json['OPLogMode'] as String,
      json['PostSendVoids'] as int,
      json['BillSettlement'] as int,
      json['EditAttendance'] as int,
      json['TransferItem'] as int,
      json['Deposits'] as int,
      json['ItemFOC'] as int,
      json['OpenPrice'] as int,
      json['OpenItems'] as int,
      json['SwitchWindow'] as int,
      json['AutoCheck'] as int,
      json['AdjustPrice'] as int,
      json['DefaultFunction'] as int,
      json['Defaultsectionname'] as String,
      json['Tablemanagement'] as int,
      json['ReprintClosedReceipt'] as int,
      json['Viewtrans'] as int,
      json['Memsearch'] as int,
      json['Edittableno'] as int,
      json['viewopentable'] as int,
      json['autoholdprintbill'] as int,
      json['VoidPromotion'] as int,
      json['opLanguage'] as String,
      json['op_promotion'] as int,
      json['opFiPo'] as int,
      json['opActiveYN'] as int,
      json['opSendSMS'] as int,
      json['previewbill'] as int,
      json['viewTransAll'] as int,
      json['opBottleManagement'] as int,
      json['SmartCardNo'] as String,
      json['opFingerprintID'] as int,
      json['opTopUpRefund'] as int,
      json['opTopUp'] as int,
      json['opMember'] as int,
      json['opMembership'] as int,
      json['opTopUpTransfer'] as int,
      json['opSplitBill'] as int,
      json['opPartialTopUpRefund'] as int,
      json['opBottleExpiry'] as int,
      json['opReprintKitchenReceipt'] as int,
      json['XZEntitlement'] as String,
      json['opWriteTicket'] as int,
      json['opReprintTopUp'] as int,
      json['opEditDeposit'] as int,
      json['opVoidDeposit'] as int,
      json['opConnectXPA'] as int,
      json['opBlitzBalance'] as int,
      json['OpUpdateHeld'] as int,
      json['ProcessKDS'] as int,
      json['ServedKDS'] as int,
      json['DisableSearchByMemId'] as int,
      json['CashTopUpMemberSearch'] as int,
      json['XZPeriod'] as int,
      json['ByTemplate'] as int,
      json['opSoldOut'] as int,
      json['opVoidMember'] as int,
      json['opViewSales'] as int,
      json['opReprintAll'] as int,
      json['ENCRYPTED'] as int,
      json['OpReopenbill'] as int,
      (json['Quota'] as num).toDouble(),
      json['opChangeSalesCtg'] as int,
      json['opReopenBillToday'] as int,
      json['SettingKDS'] as int,
      json['opPointAdjust'] as int,
      json['DiscTotalPts'] as int,
      json['opRefundDeposit'] as int,
      json['opChangeDrawer'] as int,
      json['opCombineBill'] as int,
      json['OpMaxPrintBill'] as int,
      json['DiscTotalCashless'] as int,
      json['opPrinterSetting'] as int,
    );

Map<String, dynamic> _$OperatorModelToJson(OperatorModel instance) =>
    <String, dynamic>{
      'OperatorNo': instance.OperatorNo,
      'OperatorName': instance.OperatorName,
      'PIN': instance.PIN,
      'MultiOp': instance.MultiOp,
      'MaxVoids': instance.MaxVoids,
      'MaxVoidsPerSale': instance.MaxVoidsPerSale,
      'SelectableVoids': instance.SelectableVoids,
      'VoidLastItem': instance.VoidLastItem,
      'AllVoid': instance.AllVoid,
      'VoidPayments': instance.VoidPayments,
      'DiscItemPer': instance.DiscItemPer,
      'DiscItemAmt': instance.DiscItemAmt,
      'RepeatBillDisc': instance.RepeatBillDisc,
      'FreeOfCharge': instance.FreeOfCharge,
      'SuspendBill': instance.SuspendBill,
      'ExemptTax': instance.ExemptTax,
      'StayTaxEmptOn': instance.StayTaxEmptOn,
      'RecallBill': instance.RecallBill,
      'AdjustBill': instance.AdjustBill,
      'ReprintReceipt': instance.ReprintReceipt,
      'PriceShift': instance.PriceShift,
      'OpenPriceShift': instance.OpenPriceShift,
      'XReport': instance.XReport,
      'ZReport': instance.ZReport,
      'TransferSale': instance.TransferSale,
      'TransferTable': instance.TransferTable,
      'Refunds': instance.Refunds,
      'RedeemPoints': instance.RedeemPoints,
      'ZeroSales': instance.ZeroSales,
      'CardNo': instance.CardNo,
      'Manager': instance.Manager,
      'ForceCashDeclare': instance.ForceCashDeclare,
      'OpenAnyTable': instance.OpenAnyTable,
      'TBLReservation': instance.TBLReservation,
      'MembershipNum': instance.MembershipNum,
      'ActivePromotion': instance.ActivePromotion,
      'PromotionEnds': instance.PromotionEnds,
      'ClearAndStore': instance.ClearAndStore,
      'EditSysSetup': instance.EditSysSetup,
      'PreSettlementRcpt': instance.PreSettlementRcpt,
      'LogoutAfterSale': instance.LogoutAfterSale,
      'LogoutOnTableHold': instance.LogoutOnTableHold,
      'EditKitchenMessage': instance.EditKitchenMessage,
      'OPLogMode': instance.OPLogMode,
      'PostSendVoids': instance.PostSendVoids,
      'BillSettlement': instance.BillSettlement,
      'EditAttendance': instance.EditAttendance,
      'TransferItem': instance.TransferItem,
      'Deposits': instance.Deposits,
      'ItemFOC': instance.ItemFOC,
      'OpenPrice': instance.OpenPrice,
      'OpenItems': instance.OpenItems,
      'SwitchWindow': instance.SwitchWindow,
      'AutoCheck': instance.AutoCheck,
      'AdjustPrice': instance.AdjustPrice,
      'DefaultFunction': instance.DefaultFunction,
      'Defaultsectionname': instance.Defaultsectionname,
      'Tablemanagement': instance.Tablemanagement,
      'ReprintClosedReceipt': instance.ReprintClosedReceipt,
      'Viewtrans': instance.Viewtrans,
      'Memsearch': instance.Memsearch,
      'Edittableno': instance.Edittableno,
      'viewopentable': instance.viewopentable,
      'autoholdprintbill': instance.autoholdprintbill,
      'VoidPromotion': instance.VoidPromotion,
      'opLanguage': instance.opLanguage,
      'op_promotion': instance.op_promotion,
      'opFiPo': instance.opFiPo,
      'opActiveYN': instance.opActiveYN,
      'opSendSMS': instance.opSendSMS,
      'previewbill': instance.previewbill,
      'viewTransAll': instance.viewTransAll,
      'opBottleManagement': instance.opBottleManagement,
      'SmartCardNo': instance.SmartCardNo,
      'opFingerprintID': instance.opFingerprintID,
      'opTopUpRefund': instance.opTopUpRefund,
      'opTopUp': instance.opTopUp,
      'opMember': instance.opMember,
      'opMembership': instance.opMembership,
      'opTopUpTransfer': instance.opTopUpTransfer,
      'opSplitBill': instance.opSplitBill,
      'opPartialTopUpRefund': instance.opPartialTopUpRefund,
      'opBottleExpiry': instance.opBottleExpiry,
      'opReprintKitchenReceipt': instance.opReprintKitchenReceipt,
      'XZEntitlement': instance.XZEntitlement,
      'opWriteTicket': instance.opWriteTicket,
      'opReprintTopUp': instance.opReprintTopUp,
      'opEditDeposit': instance.opEditDeposit,
      'opVoidDeposit': instance.opVoidDeposit,
      'opConnectXPA': instance.opConnectXPA,
      'opBlitzBalance': instance.opBlitzBalance,
      'OpUpdateHeld': instance.OpUpdateHeld,
      'ProcessKDS': instance.ProcessKDS,
      'ServedKDS': instance.ServedKDS,
      'DisableSearchByMemId': instance.DisableSearchByMemId,
      'CashTopUpMemberSearch': instance.CashTopUpMemberSearch,
      'XZPeriod': instance.XZPeriod,
      'ByTemplate': instance.ByTemplate,
      'opSoldOut': instance.opSoldOut,
      'opVoidMember': instance.opVoidMember,
      'opViewSales': instance.opViewSales,
      'opReprintAll': instance.opReprintAll,
      'ENCRYPTED': instance.ENCRYPTED,
      'OpReopenbill': instance.OpReopenbill,
      'Quota': instance.Quota,
      'opChangeSalesCtg': instance.opChangeSalesCtg,
      'opReopenBillToday': instance.opReopenBillToday,
      'SettingKDS': instance.SettingKDS,
      'opPointAdjust': instance.opPointAdjust,
      'DiscTotalPts': instance.DiscTotalPts,
      'opRefundDeposit': instance.opRefundDeposit,
      'opChangeDrawer': instance.opChangeDrawer,
      'opCombineBill': instance.opCombineBill,
      'OpMaxPrintBill': instance.OpMaxPrintBill,
      'DiscTotalCashless': instance.DiscTotalCashless,
      'opPrinterSetting': instance.opPrinterSetting,
    };
